### ISSUE TITLE
Submitting empty search crashes

### ISSUE THREAD

**Issue by arronm** [labs14-travel-website/frontend#53]
If you try to search with an empty string it will cause a crash

**Comment by arronm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clicking 'Roam' with no provided location will load a blank page](https://trello.com/c/LUiDFKGV/119-clicking-roam-with-no-provided-location-will-load-a-blank-page)

**Comment by josh182014** [comment]
Made search field required
