### ISSUE TITLE
Receiving an empty attractions array crashes

### ISSUE THREAD

**Issue by arronm** [labs14-travel-website/frontend#54]
If no results are found for the attraction search, and an empty array is received, the app will crash with a `cannot get length of undefined`

**Comment by arronm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Receiving zero attractions will crash the app](https://trello.com/c/G05sJCSt/121-receiving-zero-attractions-will-crash-the-app)

**Comment by josh182014** [comment]
Fixed.
